# pods are used to run and manage containers with Kubernetes

# Normally there is one container per pod but you can have more than one container in a pod.
# pods consists of one or more stroage resources and IP address in the kubernetes cluster. It basically surrounds one or more containers.
# When your running a container onnodes in the cluster think of it as your runnnig inside a pod.

# When you run a container on a node then kubernetes refers to that as scheduling. So, Kubernetes schedules pods to run on specific servers that are part of the cluster.
# When Kubernetes schedules a pod to run on a specific node, then that node will actually run the containers that are part of that pod.

# Create a simple pod running an nginx container (creating a file for kubectl to run the pod):

cat << EOF | kubectl create -f -
apiVersion: v1
kind: Pod
metadata:
  name: nginx
spec:
  containers:
  - name: nginx
    image: nginx
EOF

# Get a list of pods and verify that your new nginx pod is in the Running state:
kubectl get pods

# Shuold show something like this:
kubectl get pods
NAME    READY   STATUS    RESTARTS   AGE
nginx   1/1     Running   0          13s

# below will show all pods running on the system - these are backend system pods as they are in the kube-system namespace
# ever y object in kubernetes is in a namespace, which includes the nginx pod since its in the default namespace
kubectl get pods -n kube-system

# Get more information about your nginx pod:
# good troubleshooting command since it shows the node the pod is running on and events related to the system
kubectl describe pod nginx

# Delete the pod:
kubectl delete pod nginx